import "../styles/globals.scss";
import Head from "next/head";
import Header from "../component/header";
import SessionContext from "../contexte/session";
import App from "next/app";
import { parseCookies } from "nookies";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>NextJS Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SessionContext.Provider value={pageProps.user}>
        <Header />
        <Component {...pageProps} />
      </SessionContext.Provider>
    </>
  );
}

export default MyApp;

MyApp.getInitialProps = async (appContext) => {
  const cookies = parseCookies(appContext.ctx);
  const pageProps = await App.getInitialProps(appContext);

  if (cookies.authToken) {
    return {
      pageProps: { ...pageProps.pageProps, user: true },
    };
  }
  return pageProps;
};
